In [1]:
!pip3 install torch

In [3]:
import torch
import numpy as np

In [6]:
v=torch.tensor([1,2,3,4,5,6])
print(v.dtype)

torch.int64


In [8]:
f=torch.FloatTensor([1,2,3,4,5,6])#Float Type Tensor
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [9]:
torch.Size([6])

torch.Size([6])

In [11]:
v.view(2,3)#We can manipulate our tensor by using view method.Similar with reshape in numpy 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
reshaped_tensor=v.view(3,2)#First paratemer is our row count,second row is our col count
reshaped_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [18]:
v[3:]

tensor([4, 5, 6])

In [21]:
reshaped_tensor[1:]

tensor([[3, 4],
        [5, 6]])

In [24]:
numpy_array=np.arange(40)
numpy_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [26]:
converted_numpy_array=torch.from_numpy(numpy_array)
print(converted_numpy_array.dtype)
#As we can see we created tensor from numpy array using from_numpy method

torch.int64
